name: Deploy Multi Docker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t liceur/multi-docker -f Dockerfile.dev .
      - run: docker run -e CI=true liceur/multi-docker npm test -- --coverage
      - run: docker build -t liceur/multi-docker ./client
      - run: docker build -t liceur/multi-docker ./nginx
      - run: docker build -t liceur/multi-docker ./server
      - run: docker build -t liceur/multi-docker ./worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
